doctrine:
    dbal:
        default_connection: myproject
        connections:
            myproject:
                dbname: "%env(DATABASE_NAME)%"
                user: "%env(DATABASE_USER)%"
                password: "%env(DATABASE_PASSWORD)%"
                host: "%env(DATABASE_HOST)%"
                port: "%env(DATABASE_PORT)%"
                driver: "pdo_mysql"
                server_version: '%env(DATABASE_SERVER_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App